# Generated by Django 5.0.2 on 2025-02-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likelion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tweet_url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
