# Generated by Django 5.0.2 on 2025-02-25 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likelion', '0002_tweet_tweet_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('profile_image', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='author_profile_image',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='author_username',
        ),
        migrations.AddField(
            model_name='tweet',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='likelion.author'),
            preserve_default=False,
        ),
    ]
