# Generated by Django 5.0.2 on 2025-02-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likelion', '0004_rename_username_author_author_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='author',
        ),
        migrations.AddField(
            model_name='tweet',
            name='author_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweet',
            name='author_profile_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='author_username',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
