# Generated by Django 5.0.2 on 2025-02-25 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likelion', '0005_remove_tweet_author_tweet_author_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('profile_image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='author_profile_image',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='author_username',
        ),
        migrations.AddField(
            model_name='tweet',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='likelion.author'),
        ),
    ]
