# Generated by Django 5.0.2 on 2025-02-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likelion', '0006_author_remove_tweet_author_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
