# Generated by Django 5.0.2 on 2025-02-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likelion', '0007_alter_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
