# Generated by Django 5.0.2 on 2025-02-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likelion', '0010_remove_tweet_tweet_id_alter_tweet_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aianalysis',
            name='buy_recommendation',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='negative_score',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='positive_score',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='sell_recommendation',
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='ai_score',
            field=models.IntegerField(default=0, verbose_name=0),
            preserve_default=False,
        ),
    ]
