# Generated by Django 5.0.2 on 2025-02-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likelion', '0011_remove_aianalysis_buy_recommendation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='reasoning',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='summary',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
