# Generated by Django 5.0.2 on 2025-02-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likelion', '0012_aianalysis_reasoning_aianalysis_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='companies',
            field=models.ManyToManyField(related_name='authors', to='likelion.company'),
        ),
        migrations.AddField(
            model_name='author',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
