# Generated by Django 5.0.2 on 2025-02-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likelion', '0013_author_companies_author_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aianalysis',
            name='reasoning',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
